Add capability to obfuscate keys for all records
TykTechnologies/tyk-pump pull request #309
Opened 2021-01-29 19:35 UTC by letzya

## Description

While filtering the record I thought it's good timing to obfuscate the key. For every record, I check if it needs to be filtered out and then obfuscate the key.
There's a global config field to turn this on - obfuscate_keys
Added TestObfuscateKeys just for that obfuscation function.
Added tests for filter+obfuscation of keys in a record
Important: This PR is only useful if keys are not hashed, otherwise there's no real reason to obfuscate the key but it works for both cases.

## Related Issue

## Motivation and Context

When recording the full request body, the authorization header gets recorded as well. From obvious reasons, sometimes this is problematic for clients. For example, you don't want the people that check the analytics to have access to user's keys.
Important to note that it's not enough, that it'll be better to add such fix in the source, i.e. the gateway itself should remove this header before saving the analytic record.

## How This Has Been Tested

Wrote unit tests.

## Screenshots (if appropriate)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If pulling from your own
      fork, don't request your `master`!
- [ ] Make sure you are making a pull request against the **`master` branch** (left side). Also, you should start
      *your branch* off *our latest `master`*.
- [ ] My change requires a change to the documentation.
  - [ ] If you've changed APIs, describe what needs to be updated in the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] Modules and vendor dependencies have been updated; run `go mod tidy && go mod vendor`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] Check your code additions will not fail linting checks:
  - [ ] `go fmt -s`
  - [ ] `go vet`

2021-01-30 14:26 UTC, letzya commented on analytics/analytics.go
> -func (a *AnalyticsRecord) ObfuscateKey(authHeaderName string, decode bool) {
@tbuchaillot even those I reverted this commit, it's still showing up in the diff

2021-01-30 14:31 UTC, letzya commented on config.go
> +	obfuscateAuthHeader     ObfuscateAuthHeader        `json:"obfuscate_auth_header"`
@tbuchaillot `ObfuscateAuthHeader` struct is in master even though when rebasing - it's completely disappearing

2021-01-31 20:21 UTC, tbuchaillot requested changes
@letzya could you remove prints and unnecessary debug logs?

2021-02-01 00:15 UTC, letzya commented
@tbuchaillot removed debug. Also please check the diff in analytics/analytics_test.go

2021-02-01 13:25 UTC, tbuchaillot approved these changes
LGTM

2021-02-01 15:15 UTC, konrad-sol commented
tested on hashed and not-hashed systems -> works fine

2021-02-01 23:50 UTC, merged