[TT-5426] Updating timestamp of every record in Demo Mode
TykTechnologies/tyk-pump pull request #529
Opened 2022-11-18 21:03 UTC by mativm02

## Description

This is an annex of this PR https://github.com/TykTechnologies/tyk-pump/pull/513
## Related Issue

https://tyktech.atlassian.net/browse/TT-5426?atlOrigin=eyJpIjoiYTU4ZGI1ZWNhZTE2NGE5YWJkZmE4ZmMxMTQ3ZDljN2EiLCJwIjoiaiJ9
## Motivation and Context

## How This Has Been Tested

## Screenshots (if appropriate)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If pulling from your own
      fork, don't request your `master`!
- [ ] Make sure you are making a pull request against the **`master` branch** (left side). Also, you should start
      *your branch* off *our latest `master`*.
- [ ] My change requires a change to the documentation.
  - [ ] If you've changed APIs, describe what needs to be updated in the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] Modules and vendor dependencies have been updated; run `go mod tidy && go mod vendor`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] Check your code additions will not fail linting checks:
  - [ ] `go fmt -s`
  - [ ] `go vet`

2022-11-21 09:49 UTC, tbuchaillot requested changes

2022-11-21 09:49 UTC, tbuchaillot commented on analytics/demo/demo.go
>  				r.Day = ts.Day()
@mativm02 shouldn't Day, Month, Year, Hour fields be calculated with `nextTimestamp`?

2022-11-22 13:24 UTC, tbuchaillot approved these changes

2022-11-23 13:17 UTC, sredxny approved these changes
lgtm

2022-11-23 13:22 UTC, merged

2022-11-23 13:22 UTC, mativm02 commented
/release to release-1.7