TD-1462/add-gpac
TykTechnologies/tyk-pump pull request #565
Opened 2023-02-06 19:20 UTC by Tyk-ITS

Adding terraform files for release branch management

2023-02-07 08:10 UTC, alephnull approved these changes

2023-02-08 08:24 UTC, tbuchaillot requested changes

2023-02-08 08:24 UTC, tbuchaillot commented on ci/repo-policy/main.tf
> +	required_tests = ["1.15"]},
Can we add `CI tests` here?

2023-02-08 08:24 UTC, tbuchaillot commented on ci/repo-policy/main.tf
> +	required_tests = ["1.15"]},
Can we add `CI tests` here?

2023-02-08 20:55 UTC, ermirizio commented on ci/repo-policy/main.tf
> +	required_tests = ["1.15"]},
you mean CI tests / Go 1.16 tests ??

2023-02-10 18:44 UTC, ermirizio commented
@tbuchaillot I have done the changes can we approve and merge now?

2023-02-15 08:37 UTC, tbuchaillot approved these changes

2023-02-15 08:37 UTC, merged