[TT-8846] Updating to Go 1.19
TykTechnologies/tyk-pump pull request #652
Opened 2023-05-31 13:29 UTC by mativm02

Updating go.mod and CI jobs to use go 1.19
## Description

https://tyktech.atlassian.net/browse/TT-8846?atlOrigin=eyJpIjoiOTVlNTNjY2ExYjgxNDI2ZmE4MjIyZDc3M2Y0ZTkzMjgiLCJwIjoiaiJ9
## Related Issue

## Motivation and Context

## How This Has Been Tested

## Screenshots (if appropriate)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If pulling from your own
      fork, don't request your `master`!
- [ ] Make sure you are making a pull request against the **`master` branch** (left side). Also, you should start
      *your branch* off *our latest `master`*.
- [ ] My change requires a change to the documentation.
  - [ ] If you've changed APIs, describe what needs to be updated in the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] Modules and vendor dependencies have been updated; run `go mod tidy && go mod vendor`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] Check your code additions will not fail linting checks:
  - [ ] `go fmt -s`
  - [ ] `go vet`

2023-06-01 13:30 UTC, tbuchaillot requested changes
Added some comments and some CI jobs are failing - please have a look.

2023-06-12 15:44 UTC, ermirizio commented
@mativm02 All required changes in the code has been made, all required tests needs to pass before I apply the changes, so we can apply and merge in a synchronous way.

2023-06-15 13:14 UTC, ermirizio approved these changes

2023-06-15 13:35 UTC, tbuchaillot approved these changes

2023-06-15 13:36 UTC, merged