TT-10564 Splunk backoff retry
TykTechnologies/tyk-pump pull request #758
Opened 2023-12-28 18:02 UTC by mativm02

This PR is a duplicated of https://github.com/TykTechnologies/tyk-pump/pull/745

Introduce an expotential backoff retry mechanism for sending logs to spunk to mitigate the chance of losing logs if pump fails to send logs to spunk (i.e. due to network issue or rate limit being hit). Also fixes bug where pump not closing connections after receiving response. Also spunk responses were not being checked i.e. a `404` could be returned and pump would still mark as successful pump export.

## Description

## Related Issue

## Motivation and Context

## How This Has Been Tested

## Screenshots (if appropriate)

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If pulling from your own
      fork, don't request your `master`!
- [x] Make sure you are making a pull request against the **`master` branch** (left side). Also, you should start
      *your branch* off *our latest `master`*.
- [ ] My change requires a change to the documentation.
  - [ ] If you've changed APIs, describe what needs to be updated in the documentation.
- [x] I have updated the documentation accordingly.
- [ ] Modules and vendor dependencies have been updated; run `go mod tidy && go mod vendor`
- [x] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] Check your code additions will not fail linting checks:
  - [ ] `go fmt -s`
  - [ ] `go vet`

2023-12-28 18:22 UTC, buger commented
<!-- add-pr-comment:mongo44-murmur64 -->

**API tests result - mongo44-murmur64 env: success** :white_check_mark: 
Branch used: refs/pull/758/merge
Commit:  
Triggered by: pull_request (@mativm02)
[Execution page](https://github.com/TykTechnologies/tyk-pump/actions/runs/7350075274)

2023-12-28 18:22 UTC, buger commented
<!-- add-pr-comment:postgres15-sha256 -->

**API tests result - postgres15-sha256 env: success** :white_check_mark: 
Branch used: refs/pull/758/merge
Commit:  
Triggered by: pull_request (@mativm02)
[Execution page](https://github.com/TykTechnologies/tyk-pump/actions/runs/7350075274)

2023-12-28 18:22 UTC, buger commented
<!-- add-pr-comment:postgres15-murmur64 -->

**API tests result - postgres15-murmur64 env: success** :white_check_mark: 
Branch used: refs/pull/758/merge
Commit:  
Triggered by: pull_request (@mativm02)
[Execution page](https://github.com/TykTechnologies/tyk-pump/actions/runs/7350075274)

2023-12-28 18:22 UTC, buger commented
<!-- add-pr-comment:mongo44-sha256 -->

**API tests result - mongo44-sha256 env: success** :white_check_mark: 
Branch used: refs/pull/758/merge
Commit:  
Triggered by: pull_request (@mativm02)
[Execution page](https://github.com/TykTechnologies/tyk-pump/actions/runs/7350075274)

2023-12-28 19:05 UTC, sredxny requested changes

2023-12-28 19:05 UTC, sredxny commented on README.md
> +- `max_retries`: Max number of retries if failed to send requests to splunk HEC. Default value is `0`.
also we should say when a retry is gonna happen (explain which status codes will be considered as errors)

2023-12-28 19:05 UTC, sredxny commented on pumps/splunk_test.go
> +	cfg["max_retries"] = 1
is possible to add more use-cases? Eg: max_retries: {-1, 0, 1, 3}

2024-01-02 15:31 UTC, mativm02 commented on README.md
> +- `max_retries`: Max number of retries if failed to send requests to splunk HEC. Default value is `0`.
comment improved. thanks!

2024-01-02 15:35 UTC, sredxny approved these changes

2024-01-04 13:43 UTC, merged

2024-01-04 13:46 UTC, mativm02 commented
/release to release-1.8

2024-01-04 13:47 UTC, mativm02 commented
It's merged! Thank you for your contribution @domsolutions, it's really appreciated.

2024-01-04 15:08 UTC, domsolutions commented
> It's merged! Thank you for your contribution @domsolutions, it's really appreciated.

No problem!